Name = "Diana"
Age = 15.8
Height = 1.6
LofSquare = 5
LofRectangle = 10
HofRectangle = 5
AgeinMonth = Age * 12
AverageDeathAge = 71
YearsLeft = AverageDeathAge - Age
MinFt = 3.28084
HeightinFt = Height * MinFt
AverageHeight = 160.5
HeightDifference = Height - AverageHeight
AreaofSquare = LofSquare ** 2
VolumeofCube = LofSquare ** 3 / 2
OnenofRectangleA = LofRectangle * HofRectangle * (1/9.0)
